site_name: OnlineStats.jl
site_url: https://joshday.github.io/OnlineStats.jl/
site_description: Online Statistics for Julia
site_author: Josh Day

pages:
    - Home: index.md
    - Weighting: weight.md
    - Predictive Modeling: StatLearn.md
    - API/Examples: api.md

docs_dir: 'doc'

theme: 'material'

extra:
    palette:
        primary: 'indigo'
    author:
        github: 'joshday'
    # font:
    #     text: 'Roboto'
    #     code: 'Hack'

markdown_extensions:
    - admonition
    - codehilite(css_class=code)

extra_javascript: [
     'mathjax-config.js',
     'https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML'
]
