site_name: OnlineStats.jl
site_url: https://joshday.github.io/OnlineStats.jl/
site_description: Online Statistics for Julia
site_author: Josh Day

repo_name: 'GitHub'
repo_url: 'https://github.com/joshday/OnlineStats.jl'

pages:
    - Home: index.md
    - Weighting: weight.md
    - Callbacks: callback.md
    - Merging: merging.md
    - API/Examples: api.md

docs_dir: 'doc'
site_dir: 'doc/site'

theme: 'material'

extra:
    palette:
        primary: 'indigo'
        accent: 'blue'
    author:
        github: 'joshday'
    version: 0.6.0


markdown_extensions:
    - admonition
    - codehilite(css_class=code)
    - mdx_math:
        enable_dollar_delimiter: True

extra_javascript: [
     'mathjax-config.js',
     'https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML'
]
