site_name: OnlineStats.jl
site_url: https://joshday.github.io/OnlineStats.jl/
site_description: Online Statistics for Julia
site_author: Josh Day

pages:
    - Home: index.md
    - API: api.md

docs_dir: 'doc'

theme: 'mkdocs'
